package org.twostack.tstokenlib4j;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Before;
import org.junit.Test;
import org.twostack.bitcoin4j.PublicKey;
import org.twostack.bitcoin4j.Utils;
import org.twostack.bitcoin4j.script.Script;
import org.twostack.bitcoin4j.transaction.TransactionSignature;
import org.twostack.tstokenlib4j.lock.*;
import org.twostack.tstokenlib4j.unlock.*;

import java.io.InputStream;

import static org.junit.Assert.*;

/**
 * Validates that Java lock/unlock builders produce byte-identical output
 * to the Dart canonical builders, using test vectors generated by
 * {@code dart run tool/export_test_vectors.dart} in tstokenlib.
 */
public class CrossLanguageVectorTest {

    private JsonNode root;
    private JsonNode keyMaterial;

    @Before
    public void setUp() throws Exception {
        InputStream is = getClass().getClassLoader()
                .getResourceAsStream("cross_language_vectors.json");
        assertNotNull("Test vectors file not found on classpath", is);
        ObjectMapper mapper = new ObjectMapper();
        root = mapper.readTree(is);
        keyMaterial = root.get("keyMaterial");
    }

    private JsonNode findVector(String name) {
        for (JsonNode v : root.get("vectors")) {
            if (name.equals(v.get("name").asText())) {
                return v;
            }
        }
        fail("Vector not found: " + name);
        return null;
    }

    private void assertScriptHex(String expected, Script actual, String vectorName) {
        String actualHex = Utils.HEX.encode(actual.getProgram());
        assertEquals("Script mismatch for " + vectorName, expected, actualHex);
    }

    // ──── Lock Builders ────────────────────────────────────────────

    @Test
    public void testModP2PKHLock() {
        JsonNode v = findVector("MOD_P2PKH_LOCK");
        JsonNode inputs = v.get("inputs");
        byte[] ownerPKH = Utils.HEX.decode(inputs.get("ownerPKH").asText());

        ModP2PKHLockBuilder builder = new ModP2PKHLockBuilder(ownerPKH);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getLockingScript(), "MOD_P2PKH_LOCK");
    }

    @Test
    public void testPP1NftLock() {
        JsonNode v = findVector("PP1_NFT_LOCK");
        JsonNode inputs = v.get("inputs");
        byte[] ownerPKH = Utils.HEX.decode(inputs.get("ownerPKH").asText());
        byte[] tokenId = Utils.HEX.decode(inputs.get("tokenId").asText());
        byte[] rabinPubKeyHash = Utils.HEX.decode(inputs.get("rabinPubKeyHash").asText());

        PP1NftLockBuilder builder = new PP1NftLockBuilder(ownerPKH, tokenId, rabinPubKeyHash);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getLockingScript(), "PP1_NFT_LOCK");
    }

    @Test
    public void testPP1FtLock() {
        JsonNode v = findVector("PP1_FT_LOCK");
        JsonNode inputs = v.get("inputs");
        byte[] ownerPKH = Utils.HEX.decode(inputs.get("ownerPKH").asText());
        byte[] tokenId = Utils.HEX.decode(inputs.get("tokenId").asText());
        byte[] rabinPubKeyHash = Utils.HEX.decode(inputs.get("rabinPubKeyHash").asText());
        long amount = inputs.get("amount").asLong();

        PP1FtLockBuilder builder = new PP1FtLockBuilder(ownerPKH, tokenId, rabinPubKeyHash, amount);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getLockingScript(), "PP1_FT_LOCK");
    }

    @Test
    public void testPP2Lock() {
        JsonNode v = findVector("PP2_LOCK");
        JsonNode inputs = v.get("inputs");
        byte[] outpoint = Utils.HEX.decode(inputs.get("outpoint").asText());
        byte[] witnessChangePKH = Utils.HEX.decode(inputs.get("witnessChangePKH").asText());
        long witnessChangeAmount = inputs.get("witnessChangeAmount").asLong();
        byte[] ownerPKH = Utils.HEX.decode(inputs.get("ownerPKH").asText());

        PP2LockBuilder builder = new PP2LockBuilder(outpoint, witnessChangePKH, witnessChangeAmount, ownerPKH);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getLockingScript(), "PP2_LOCK");
    }

    @Test
    public void testPP2FtLock() {
        JsonNode v = findVector("PP2_FT_LOCK");
        JsonNode inputs = v.get("inputs");
        byte[] outpoint = Utils.HEX.decode(inputs.get("outpoint").asText());
        byte[] witnessChangePKH = Utils.HEX.decode(inputs.get("witnessChangePKH").asText());
        long witnessChangeAmount = inputs.get("witnessChangeAmount").asLong();
        byte[] ownerPKH = Utils.HEX.decode(inputs.get("ownerPKH").asText());
        int pp1FtOutputIndex = inputs.get("pp1FtOutputIndex").asInt();
        int pp2OutputIndex = inputs.get("pp2OutputIndex").asInt();

        PP2FtLockBuilder builder = new PP2FtLockBuilder(outpoint, witnessChangePKH, witnessChangeAmount, ownerPKH, pp1FtOutputIndex, pp2OutputIndex);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getLockingScript(), "PP2_FT_LOCK");
    }

    // ──── Unlock Builders ──────────────────────────────────────────

    @Test
    public void testModP2PKHUnlock() throws Exception {
        JsonNode v = findVector("MOD_P2PKH_UNLOCK");
        JsonNode inputs = v.get("inputs");
        PublicKey pubKey = PublicKey.fromHex(inputs.get("signerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        ModP2PKHUnlockBuilder builder = new ModP2PKHUnlockBuilder(pubKey);
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "MOD_P2PKH_UNLOCK");
    }

    @Test
    public void testPP2UnlockNormal() {
        JsonNode v = findVector("PP2_UNLOCK_NORMAL");
        JsonNode inputs = v.get("inputs");
        byte[] outpointTxId = Utils.HEX.decode(inputs.get("outpointTxId").asText());

        PP2UnlockBuilder builder = PP2UnlockBuilder.forNormal(outpointTxId);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP2_UNLOCK_NORMAL");
    }

    @Test
    public void testPP2UnlockBurn() throws Exception {
        JsonNode v = findVector("PP2_UNLOCK_BURN");
        JsonNode inputs = v.get("inputs");
        PublicKey pubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP2UnlockBuilder builder = PP2UnlockBuilder.forBurn(pubKey);
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP2_UNLOCK_BURN");
    }

    @Test
    public void testPP2FtUnlockNormal() {
        JsonNode v = findVector("PP2_FT_UNLOCK_NORMAL");
        JsonNode inputs = v.get("inputs");
        byte[] outpointTxId = Utils.HEX.decode(inputs.get("outpointTxId").asText());

        PP2FtUnlockBuilder builder = PP2FtUnlockBuilder.forNormal(outpointTxId);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP2_FT_UNLOCK_NORMAL");
    }

    @Test
    public void testPP2FtUnlockBurn() throws Exception {
        JsonNode v = findVector("PP2_FT_UNLOCK_BURN");
        JsonNode inputs = v.get("inputs");
        PublicKey pubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP2FtUnlockBuilder builder = PP2FtUnlockBuilder.forBurn(pubKey);
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP2_FT_UNLOCK_BURN");
    }

    @Test
    public void testPP1NftUnlockIssuance() throws Exception {
        JsonNode v = findVector("PP1_NFT_UNLOCK_ISSUANCE");
        JsonNode inputs = v.get("inputs");

        PP1NftUnlockBuilder builder = PP1NftUnlockBuilder.forIssuance(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("witnessFundingTxId").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText()),
                Utils.HEX.decode(inputs.get("rabinN").asText()),
                Utils.HEX.decode(inputs.get("rabinS").asText()),
                inputs.get("rabinPadding").asLong(),
                Utils.HEX.decode(inputs.get("identityTxId").asText()),
                Utils.HEX.decode(inputs.get("ed25519PubKey").asText())
        );
        // Issuance in Dart requires a signature to be present even though it's not pushed
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_NFT_UNLOCK_ISSUANCE");
    }

    @Test
    public void testPP1NftUnlockTransfer() throws Exception {
        JsonNode v = findVector("PP1_NFT_UNLOCK_TRANSFER");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1NftUnlockBuilder builder = PP1NftUnlockBuilder.forTransfer(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("pp2Output").asText()),
                ownerPubKey,
                Utils.HEX.decode(inputs.get("changePKH").asText()),
                inputs.get("changeAmount").asLong(),
                Utils.HEX.decode(inputs.get("tokenLHS").asText()),
                Utils.HEX.decode(inputs.get("prevTokenTx").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText())
        );
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_NFT_UNLOCK_TRANSFER");
    }

    @Test
    public void testPP1NftUnlockBurn() throws Exception {
        JsonNode v = findVector("PP1_NFT_UNLOCK_BURN");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1NftUnlockBuilder builder = PP1NftUnlockBuilder.forBurn(ownerPubKey);
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_NFT_UNLOCK_BURN");
    }

    @Test
    public void testPP1FtUnlockMint() {
        JsonNode v = findVector("PP1_FT_UNLOCK_MINT");
        JsonNode inputs = v.get("inputs");

        PP1FtUnlockBuilder builder = PP1FtUnlockBuilder.forMint(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("witnessFundingTxId").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText()),
                Utils.HEX.decode(inputs.get("rabinN").asText()),
                Utils.HEX.decode(inputs.get("rabinS").asText()),
                inputs.get("rabinPadding").asInt(),
                Utils.HEX.decode(inputs.get("identityTxId").asText()),
                Utils.HEX.decode(inputs.get("ed25519PubKey").asText())
        );
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_FT_UNLOCK_MINT");
    }

    @Test
    public void testPP1FtUnlockTransfer() throws Exception {
        JsonNode v = findVector("PP1_FT_UNLOCK_TRANSFER");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1FtUnlockBuilder builder = PP1FtUnlockBuilder.forTransfer(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("pp2Output").asText()),
                ownerPubKey,
                Utils.HEX.decode(inputs.get("changePKH").asText()),
                inputs.get("changeAmount").asLong(),
                Utils.HEX.decode(inputs.get("tokenLHS").asText()),
                Utils.HEX.decode(inputs.get("prevTokenTx").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText()),
                inputs.get("parentOutputCount").asInt(),
                inputs.get("parentPP1FtIndex").asInt()
        );
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_FT_UNLOCK_TRANSFER");
    }

    @Test
    public void testPP1FtUnlockSplitTransfer() throws Exception {
        JsonNode v = findVector("PP1_FT_UNLOCK_SPLIT_TRANSFER");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1FtUnlockBuilder builder = PP1FtUnlockBuilder.forSplitTransfer(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("pp2RecipientOutput").asText()),
                Utils.HEX.decode(inputs.get("pp2ChangeOutput").asText()),
                ownerPubKey,
                Utils.HEX.decode(inputs.get("changePKH").asText()),
                inputs.get("changeAmount").asLong(),
                Utils.HEX.decode(inputs.get("tokenLHS").asText()),
                Utils.HEX.decode(inputs.get("prevTokenTx").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText()),
                inputs.get("recipientAmount").asLong(),
                inputs.get("tokenChangeAmount").asLong(),
                Utils.HEX.decode(inputs.get("recipientPKH").asText()),
                inputs.get("myOutputIndex").asInt(),
                inputs.get("parentOutputCount").asInt(),
                inputs.get("parentPP1FtIndex").asInt()
        );
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_FT_UNLOCK_SPLIT_TRANSFER");
    }

    @Test
    public void testPP1FtUnlockMerge() throws Exception {
        JsonNode v = findVector("PP1_FT_UNLOCK_MERGE");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1FtUnlockBuilder builder = PP1FtUnlockBuilder.forMerge(
                Utils.HEX.decode(inputs.get("preImage").asText()),
                Utils.HEX.decode(inputs.get("pp2Output").asText()),
                ownerPubKey,
                Utils.HEX.decode(inputs.get("changePKH").asText()),
                inputs.get("changeAmount").asLong(),
                Utils.HEX.decode(inputs.get("tokenLHS").asText()),
                Utils.HEX.decode(inputs.get("prevTokenTxA").asText()),
                Utils.HEX.decode(inputs.get("prevTokenTxB").asText()),
                Utils.HEX.decode(inputs.get("witnessPadding").asText()),
                inputs.get("parentOutputCountA").asInt(),
                inputs.get("parentOutputCountB").asInt(),
                inputs.get("parentPP1FtIndexA").asInt(),
                inputs.get("parentPP1FtIndexB").asInt()
        );
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_FT_UNLOCK_MERGE");
    }

    @Test
    public void testPP1FtUnlockBurn() throws Exception {
        JsonNode v = findVector("PP1_FT_UNLOCK_BURN");
        JsonNode inputs = v.get("inputs");
        PublicKey ownerPubKey = PublicKey.fromHex(inputs.get("ownerPubKeyHex").asText());
        TransactionSignature sig = TransactionSignature.fromTxFormat(inputs.get("signatureTxFormatHex").asText());

        PP1FtUnlockBuilder builder = PP1FtUnlockBuilder.forBurn(ownerPubKey);
        builder.addSignature(sig);
        assertScriptHex(v.get("expectedScriptHex").asText(), builder.getUnlockingScript(), "PP1_FT_UNLOCK_BURN");
    }
}
